{
 "title": "Usage Insights - 4 - Alertmanager",
 "tags": [
  "alertmanager",
  "grafanacloud"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alertmanager_id",
    "label": "Alertmanager Instance",
    "query": "grafanacloud_instance_alertmanager_info{}"
   }
  ]
 },
 "panels": [
  { "title": "Alertmanager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Alerts Configured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafanacloud_instance_alertmanager_alerts{id=~\"$alertmanager_id\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Silences",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafanacloud_instance_alertmanager_silences{id=~\"$alertmanager_id\", state=\"active\"})"
    }
   ]
  },
  {
   "title": "Alertmanager Logs Volume",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({instance_type=\"alerts\", instance_id=~\"$alertmanager_id\"} | logfmt [$__interval]))",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Alertmanager Issues",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{instance_type=\"alerts\", instance_id=~\"$alertmanager_id\"} | logfmt | __error__ = \"\" | level=~\"(warn|error)\" | user=~\"$alertmanager_id\""
    }
   ]
  }
 ]
}