{
 "title": "Billing/Usage",
 "tags": [
  "billing",
  "grafanacloud"
 ],
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  { "title": "Billable Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_total_overage", "legendFormat": "Total additional usage" },
    {
     "expr": "grafanacloud_org_spend_commit_credit_total > 0",
     "legendFormat": "Initial spend committed"
    },
    {
     "expr": "grafanacloud_org_spend_commit_balance_total > 0",
     "legendFormat": "Last month spend commit balance"
    }
   ]
  },
  {
   "title": "How Billing Works",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "content": "Metrics, Logs and Traces are billed based on ingestion. For Metrics, we bill based on the number of active series using the 95th percentile during the period. [Learn more here](\nhttps://grafana.com/docs/grafana-cloud/billing-and-usage/).\n\nThis dashboard contains:\n- a detailed breakdown of your usage\n- an estimate of your bill for the month\n\nFor your final bill, refer to your invoices. To reconcile these invoices with this dashboard, you'll need to view month-end data a few hours after midnight. See [how to reconcile invoices](https://grafana.com/docs/grafana-cloud/billing-and-usage/#reconcile-invoices).\n"
  },
  {
   "title": "Current Billable Metrics Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_billable_series",
     "legendFormat": "Graphite"
    }
   ]
  },
  {
   "title": "Current Metrics Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_overage",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_overage",
     "legendFormat": "Graphite"
    }
   ]
  },
  {
   "title": "Total Billable Metrics Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series",
     "legendFormat": "Billable Series"
    },
    {
     "expr": "grafanacloud_org_metrics_overage",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_metrics_included_series",
     "legendFormat": "Included Series"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_billable_series",
     "legendFormat": "Billable Graphite Series"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_overage",
     "legendFormat": "Additional Graphite Usage Amount"
    },
    {
     "expr": "grafanacloud_org_graphite_metrics_included_series",
     "legendFormat": "Included Graphite Series"
    },
    {
     "expr": "max(grafanacloud_instance_billable_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_metrics_billable_series) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_metrics_overage * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "title": "Current Billable Logs Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_logs_usage" }
   ]
  },
  {
   "title": "Current Logs Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_logs_overage" }
   ]
  },
  {
   "title": "Total Billable Logs Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    { "expr": "grafanacloud_org_logs_usage", "legendFormat": "Billable Usage" },
    { "expr": "grafanacloud_org_logs_overage", "legendFormat": "Additional Usage Amount" },
    {
     "expr": "grafanacloud_org_logs_included_usage",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_logs_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_overage * on (id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "title": "Current Billable Traces Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_traces_usage" }
   ]
  },
  {
   "title": "Current Traces Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_traces_overage"
    }
   ]
  },
  {
   "title": "Total Billable Traces Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    { "expr": "grafanacloud_org_traces_usage", "legendFormat": "Billable Usage" },
    {
     "expr": "grafanacloud_org_traces_overage",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_traces_included_usage",
     "legendFormat": "Included Usage"
    },
    {
     "expr": "max(grafanacloud_traces_instance_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_traces_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_traces_overage * on (id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "Additional Usage Amount - {{ name }}"
    }
   ]
  },
  {
   "title": "Current Billable Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users",
     "legendFormat": "Total Unique Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_grafana",
     "legendFormat": "Grafana Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_oncall",
     "legendFormat": "OnCall Users"
    }
   ]
  },
  {
   "title": "Current Additional Users Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_overage"
    }
   ]
  },
  {
   "title": "Total Billable Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafanacloud_org_grafana_billable_users",
     "legendFormat": "Billable Users"
    },
    {
     "expr": "grafanacloud_org_grafana_overage",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_grafana_included_users",
     "legendFormat": "Included Users"
    }
   ]
  },
  {
   "title": "Billable Users Breakdown",
   "type": "graph",
   "description": "Total Billable Users represents the number of unique Grafana and OnCall users across all instances. A user that is active in both Grafana and OnCall will be counted in each service separately, but will only be counted once in Total Billable Users. See [Billing for Active Users](https://grafana.com/docs/grafana-cloud/fundamentals/billing-and-usage/#billing-for-active-users) for additional information.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafanacloud_org_billable_users_grafana",
     "legendFormat": "Grafana Users"
    },
    {
     "expr": "grafanacloud_org_billable_users_oncall",
     "legendFormat": "OnCall users"
    }
   ]
  },
  {
   "title": "Logs Retention (Advanced feature)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Billable Logs Retention Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_logs_retention_usage"
      }
     ]
    },
    {
     "title": "Current Logs Retention Usage Amount",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "prefix:$" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_logs_retention_overage"
      }
     ]
    },
    {
     "title": "Total Billable Logs Retention Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "expr": "grafanacloud_org_logs_retention_usage",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "grafanacloud_org_logs_retention_overage",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_logs_retention_included_usage",
       "legendFormat": "Included Usage"
      },
      {
       "expr": "max(grafanacloud_logs_instance_retention_usage) by (id) / ignoring(id) group_left() max(grafanacloud_org_logs_retention_usage) by (id) * ignoring(id,org_id,cluster) group_left() grafanacloud_org_logs_retention_overage * on (id) group_left(name) grafanacloud_logs_instance_info",
       "legendFormat": "Additional Usage Amount - {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "k6 Virtual User Hours (VUh)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Billable VUh Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "VUh" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_usage"
      }
     ]
    },
    {
     "title": "Current VUh Usage Amount",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "prefix:$" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_overage"
      }
     ]
    },
    {
     "title": "Total Billable Virtual User Hours (VUh)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 41 },
     "yaxes": [
      { "format": "VUh" }
     ],
     "targets": [
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_usage",
       "legendFormat": "Billable Usage"
      },
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_overage",
       "legendFormat": "Additional Usage Amount"
      },
      {
       "expr": "grafanacloud_org_k6_virtual_user_hours_included_usage",
       "legendFormat": "Included Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Incident Response & Management (IRM) Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Billable IRM Users",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "grafanacloud_org_irm_users" }
     ]
    },
    {
     "title": "Current IRM Users Amount",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "prefix:$" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_irm_users_overage"
      }
     ]
    },
    {
     "title": "Total Billable IRM Users",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "grafanacloud_org_irm_users", "legendFormat": "Billable Users" },
      {
       "expr": "grafanacloud_org_irm_users_overage",
       "legendFormat": "Additional Users Amount"
      },
      {
       "expr": "grafanacloud_org_irm_included_users",
       "legendFormat": "Included Users"
      }
     ]
    }
   ]
  },
  {
   "title": "Enterprise Plugin Add-on Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Billable Users",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_plugin_users"
      }
     ]
    },
    {
     "title": "Current Users Amount",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "prefix:$" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_plugin_users_overage"
      }
     ]
    },
    {
     "title": "Total Billable Users",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grafanacloud_org_grafana_plugin_users",
       "legendFormat": "Billable Users"
      },
      {
       "expr": "grafanacloud_org_grafana_plugin_users_overage",
       "legendFormat": "Additional Usage Amount"
      }
     ]
    }
   ]
  },
  { "title": "Metrics Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Metrics Active Series",
   "type": "graph",
   "description": "Shows:\n\n- Total active-series per managed Prometheus metrics service (GrafanaCloud Stack).\n\n- Active-series ingested in the Datadog format\n\n- Active-series ingested in the Influx format\n\n- Active-series per installed integration (with default job-name in Agent config)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(grafanacloud_instance_active_series) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max(grafanacloud_instance_active_datadog_series > 0) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}: Datadog format"
    },
    {
     "expr": "max(grafanacloud_instance_active_influx_series > 0) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}: Influx format"
    },
    {
     "expr": "max(grafanacloud_instance_active_integration_series) by (id, integration) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}: {{integration}} intg."
    }
   ]
  },
  {
   "title": "Highest DPM per series, by stack (top 3 stacks)",
   "type": "gauge",
   "description": "Shows up to 3 of your stacks, ordered by those with the greatest average DPM per active-series.\n\nThis value calculated at the current instant. ie. `now()`",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  max by(id, name) (\n    60 * grafanacloud_instance_samples_per_second\n    / grafanacloud_instance_active_series\n\n    * on(id) group_left(name) grafanacloud_instance_info\n  )\n)\n"
    },
    {
     "expr": "scalar(grafanacloud_org_metrics_included_dpm_per_series)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "content": "This gauge panel displays your highest (or only) metrics ingestion instances at Grafana Cloud, and their respective current DPM (Data Points per Minute). Your plan has a default included DPM, shown in green in the gauge. Anything above that default is billed in overages above your plan's cost per 1000 active series.\n\nTo learn more about how DPM and active series affects your billing see our article here: [Active Series and DPM](https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/). To control or change your DPM see: [Changing your metrics scrape interval](https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/)."
  },
  {
   "title": "Metrics Ingestion Rate (DPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(grafanacloud_instance_samples_per_second * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Metric Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(max(grafanacloud_instance_samples_discarded_per_second) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Metrics Instance Usage Group Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active series per usage group",
     "type": "graph",
     "description": "The panel displays active series broken down by user-defined usage groups, and the number of active series not assigned to any group. This can be used for internal back-charging. Read the [blog post on the topic](https://grafana.com/blog/2022/08/11/grafana-usage-insights-how-to-track-who-is-sending-what-metrics-to-your-stack-in-grafana-cloud/) to learn more about this feature. \n\n Please contact support to get this set up.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(grafanacloud_instance_active_usage_group_series) by (id, group) * on (id) group_left(name) grafanacloud_instance_info",
       "legendFormat": "{{name}}: group {{group}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Logs Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Ingested Logs by Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((grafanacloud_logs_instance_bytes_received_per_second * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Log Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second) by (id, reason) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  { "title": "Traces Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Traces Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Ingested Traces by Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((grafanacloud_traces_instance_bytes_received_per_second * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_traces_instance_info or vector(0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "si:/s" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_traces_instance_discarded_spans_total:rate5m) by (id, reason) * on(id) group_left(name) grafanacloud_traces_instance_info",
     "legendFormat": "{{name}} - {{reason}}"
    }
   ]
  },
  { "title": "Grafana Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Active Grafana Users (last 30 days)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_grafana_instance_active_user_count) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Grafana Dashboards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_grafana_instance_dashboard_count) by (id) * on(id) group_left(name) grafanacloud_grafana_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}