{
 "title": "Alerts",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "alertmanager",
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active alerts",
   "type": "timeseries",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max_over_time(grafanacloud_instance_alertmanager_alerts{state=\"active\"}[$__interval])",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Alerts Activation History",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(grafanacloud_instance_alertmanager_alerts[$__interval])",
     "legendFormat": "{{cluster}}: {{state}}"
    }
   ]
  },
  {
   "title": "Suppressed alerts",
   "type": "timeseries",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(grafanacloud_instance_alertmanager_alerts{state=\"suppressed\"}[$__interval])",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Unprocessed alerts",
   "type": "timeseries",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(grafanacloud_instance_alertmanager_alerts{state=\"unprocessed\"}[$__interval])",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Active silences",
   "type": "timeseries",
   "description": "Current number of active silences.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(grafanacloud_instance_alertmanager_silences{state=\"active\"}[$__interval])",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}