{
 "title": "Metrics exploration dashboard",
 "description": "Use this to explore new metrics, as a stepping stone to building new dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric", "query": { "query": "label_values(__name__)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboard for exploring and understanding new metrics\n\nWhen we add new metrics from a new service, it's useful to explore them and try to get a sense for them.\nThe grafana explore panel is useful for looking at metrics one at a time, but this dashboard can be used to quickly glance at a bunch of metrics and compare them.\nSee this [guide](https://grafana.com/blog/2022/06/06/grafana-dashboards-a-complete-guide-to-all-the-different-types-you-can-build/#metrics-exploration-dashboards) for more info"
   }
  },
  { "title": "$metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "metric" },
  {
   "title": "Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    { "expr": "avg without (pod) ($metric)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    { "expr": "sum without (pod) ($metric)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg without (pod) (rate($metric[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum without (pod) (rate($metric[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}