{
 "title": "General Monitoring Dashboard for M1 (Devnet)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"integrations/kubernetes/kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "api_name",
    "query": {}
   },
   {
    "name": "apigateway_stage",
    "query": {}
   },
   { "name": "beaconchain_apikey", "query": "cy82V2JSeU9WUjk4bjR3Qm40em4u" }
  ]
 },
 "panels": [
  {
   "title": "eigenPod_Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "devnetGraphScraper_eigenPod_Count",
     "legendFormat": "eigenPod_Count"
    }
   ]
  },
  {
   "title": "eigen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "devnetGraphScraper_currentStrategyTVL_rEthDeposits",
     "legendFormat": "eigen Deposits"
    },
    {
     "expr": "devnetGraphScraper_currentStrategyTVL_rEthPendingWithdrawals",
     "legendFormat": "PendingWithdrawals"
    },
    {
     "expr": "devnetGraphScraper_currentStrategyTVL_rEthWithdrawals",
     "legendFormat": "Withdrawals"
    }
   ]
  },
  {
   "title": "weth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "devnetGraphScraper_currentStrategyTVL_stEthDeposits / 1e18",
     "legendFormat": "Deposits"
    },
    {
     "expr": "devnetGraphScraper_currentStrategyTVL_stEthPendingWithdrawals / 1e18",
     "legendFormat": "PendingWithdrawals"
    },
    {
     "expr": "devnetGraphScraper_currentStrategyTVL_stEthWithdrawals / 1e18",
     "legendFormat": "Withdrawals"
    }
   ]
  },
  {
   "title": "anomalies_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "devnetGraphScraper_anomalies_total",
     "legendFormat": "anomalies_total"
    }
   ]
  },
  {
   "title": "Are we having trouble? (no data here = good)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 } },
  {
   "title": "K8s Pods Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "(Sentry) Frontend Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Network Errors" } },
   "targets": [
    {
     "issuesQuery": "ErrorType:\"Network Error\"",
     "projectIds": [ "4504923624833025" ],
     "statsCategory": [ "transaction" ],
     "statsFields": [ "sum(times_seen)" ],
     "statsGroupBy": [ "category" ]
    }
   ]
  },
  {
   "title": "# of Eigenpods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"data.variable.integerValue\"",
     "url": "https://e2blmxaczk.execute-api.us-east-1.amazonaws.com/devnet/graph-internal",
     "url_options": {
      "body_content_type": "text/plain",
      "body_graphql_query": "{\n  variable(id: \"podCount\") {\n    id\n    integerValue\n  }\n}",
      "body_type": "graphql",
      "data": "{\n  variable(id: \"podCount\") {\n    id\n    integerValue\n  }\n}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "chaind sync distance (epochs)",
   "type": "gauge",
   "description": "number of epochs chaind is behind lighthouse clients",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$chaind_head_epoch - $lighthouse_head_epoch",
     "type": "math"
    }
   ]
  },
  {
   "title": "lighthouse-0 sync distance (slot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse_0 - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "lighthouse-1 sync distance (slot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "lighthouse-2 sync distance (slot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "thegraph sync distance (blocks)",
   "type": "gauge",
   "description": "number of slots thegraph is behind nethermind clients",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$thegraph_head - $nethermind_head",
     "type": "math"
    }
   ]
  },
  {
   "title": "nethermin-0 sync distance (block)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "options": {
    "content": "Can't get the EL sync distance to show. Check https://eigenlayer.grafana.net/d/ZbOKkYBVk/general-monitoring-dashboard-for-m1?orgId=1&refresh=10s&from=1680568307926&to=1680571907926&viewPanel=18"
   }
  },
  {
   "title": "API Gateway traffic (main backend entrypoint)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "#Reqs (all incoming)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Stage": "$apigateway_stage" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Stage": "$apigateway_stage" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Avg Duration (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Max Duration (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "5XXError",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "$apigateway_stage" },
     "id": "e500",
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "4XXError",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "$apigateway_stage" },
     "id": "e400",
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "options": {
    "content": "- routes\n  - /price: cached proxy to coingecko\n  - /graph: retrieves information from thegraph for LSD frontend\n  - /restaking/pods/{address}/summary: calls the lambda to get solo staker information"
   }
  },
  { "type": "text", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 }, "options": { "content": "Info" } },
  {
   "title": "Lambda RED (Requests, Errors, Duration) - load-test 1req/min traffic always present",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Lambda # Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "dimensions": {
      "Resource": "eigenlayer-dev-usea1-devnet-rewards"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Invocation Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "dimensions": {
      "Resource": "eigenlayer-dev-usea1-devnet-rewards"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "dimensions": {
      "Resource": "eigenlayer-dev-usea1-devnet-rewards"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Kubernetes Instances + Pods (CPU, memory, storage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Node/Instance Level Resource Usage",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "options": {
    "content": "- (public subnet) clel nodegroup\n  - runs CL (lighthouse) + EL (nethermind) clients\n- (private subnet) default nodegroup\n  - runs CL (chaind) and EL (thegraph) indexers\n\nNote: Spike traffic is explained by chaind writing at epoch boundaries (~ every 6 mins)\n\nTODO: relabel the instances with subnet info so that we can compare indexing vs query work. We might even want to duplicate every dashboard, since we'll likely mostly be interested in the private subnet serving read requests.  "
   }
  },
  {
   "title": "Pod Level Resource Usage",
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 46 },
   "options": {
    "content": "- clients\n  - (consensus) lighthouse x3\n  - (execution) nethermind x3\n- indexers\n  - (execution) thegraph\n    - query nodes          x3\n    - indexer              x1\n    - ipfs                 x1\n  - (consensus) chaind     x1"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 46 },
   "options": {
    "content": "Note: it's normal for nethermind client to use >20G of RAM"
   }
  },
  {
   "title": "$cluster System CPU percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cluster, node) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) / sum by(cluster, node) (kube_node_status_capacity{resource=\"cpu\", cluster=~\"$cluster\"}) ",
     "legendFormat": "{{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "$cluster ($namespace namespaces) Pod vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum  (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cluster, node) (node_namespace_pod_container:container_memory_working_set_bytes{}) / sum by(cluster, node) (kube_node_status_capacity{resource=\"memory\", cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "$cluster/$namespace Pod Memory WSS (32G/private-node, 8G/public-node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", namespace=~\"$namespace\", container!=\"\", image!=\"\", cluster=~\"$cluster\"}) by (pod) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster/$namespace Persistent Volume %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n(kubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"$namespace\", cluster=~\"$cluster\"} -\nkubelet_volume_stats_available_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) / \nkubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients, graph, chaind head sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "beaconcha.in head epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"data.epoch\"",
     "url": "https://goerli.beaconcha.in/api/v1/slot/latest?apikey=$beaconchain_apikey",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "beaconcha.in head slot",
   "type": "stat",
   "description": "head block of execution client",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"data.slot\" ",
     "url": "https://goerli.beaconcha.in/api/v1/slot/latest?apikey=$beaconchain_apikey",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    }
   ]
  },
  {
   "title": "infura head block",
   "type": "stat",
   "description": "head slot of execution client",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "json_options": {
      "root_is_not_array": false
     },
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"result\"",
     "url": "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "CL head epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{cluster=\"eigenlayer-dev-usea1-devnet\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CL head epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slotclock_present_slot{cluster=\"eigenlayer-dev-usea1-devnet\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "EL clients head block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks{cluster=\"eigenlayer-dev-usea1-devnet\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chaind head epoch",
   "type": "stat",
   "description": "Last chaind processed slot",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaind_validators_latest_epoch{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 90 },
   "options": {
    "content": "TODO: --->\nfix the thegraph panel to only show the running instance\n\n<--- TODO --->:\nGeneral issue with restarting leaves a duplicate"
   }
  },
  {
   "title": "The Graph head",
   "type": "stat",
   "description": "last thegraph processed block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_head{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}, {{ deployment }}"
    }
   ]
  }
 ]
}