{
 "title": "preprod-smart-contract-statistics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "totalUsers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "preprodGraphScraper_totalUsers_count",
     "legendFormat": "totalUsers"
    }
   ]
  },
  {
   "title": "anomality",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "preprodGraphScraper_anomalies_critical",
     "legendFormat": "critical"
    },
    {
     "expr": "preprodGraphScraper_anomalies_total",
     "legendFormat": "total"
    },
    {
     "expr": "preprodGraphScraper_anomalies_warning",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "eigenPod Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "preprodGraphScraper_eigenPod_Count",
     "legendFormat": "pod count"
    }
   ]
  },
  { "title": "EigenPod Withdrawal 1e18", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "pendingWithdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentEigenPodWithdrawal_pendingWithdrawals / 1e18",
     "legendFormat": "pendingWithdrawals"
    }
   ]
  },
  {
   "title": "withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentEigenPodWithdrawal_withdrawals / 1e18",
     "legendFormat": "withdrawals"
    }
   ]
  },
  { "title": "stEth 1e18", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Deposits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_stEthDeposits\n{namespace=\"graph-scraper\"} / 1e18",
     "legendFormat": "deposits"
    }
   ]
  },
  {
   "title": "PendingWithdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_stEthPendingWithdrawals{namespace=\"graph-scraper\"} / 1e18",
     "legendFormat": "pendingWithdrawals"
    }
   ]
  },
  {
   "title": "Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_stEthWithdrawals{namespace=\"graph-scraper\"} / 1e18",
     "legendFormat": "withdrawals"
    }
   ]
  },
  { "title": "rEth 1e18", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Deposits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_rEthDeposits\n{namespace=\"graph-scraper\"} / 1e18",
     "legendFormat": "deposits"
    }
   ]
  },
  {
   "title": "PendingWithdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_rEthPendingWithdrawals{namespace=\"graph-scraper\"} / 1e18",
     "legendFormat": "pendingWithdrawals"
    }
   ]
  },
  {
   "title": "Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_rEthWithdrawals{namespace=\"graph-scraper\"} / 1e18",
     "legendFormat": "withdrawals"
    }
   ]
  }
 ]
}