{
 "title": "General Monitoring Dashboard for M1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Chain", "label": "chain", "query": "devnet, goerli, mainnet" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"integrations/kubernetes/kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "api_name",
    "query": {}
   },
   {
    "name": "apigateway_stage",
    "query": {}
   },
   { "name": "beaconchain_apikey", "query": "cy82V2JSeU9WUjk4bjR3Qm40em4u" },
   { "name": "cloudwatchDatasource", "label": "cloudwatchDatasource", "query": "cloudwatch" },
   { "name": "environment", "label": "environment", "query": "dev, preprod, prod" }
  ]
 },
 "panels": [
  {
   "title": "eigenPod Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "preprodGraphScraper_eigenPod_Count{cluster=\"$cluster\"}",
     "legendFormat": "pod count"
    }
   ]
  },
  {
   "title": "rETH currentStrategyTVL (unit 1e18)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_rEthDeposits\n{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "deposits"
    },
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_rEthPendingWithdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "pendingWithdrawals"
    },
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_rEthWithdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "withdrawals"
    }
   ]
  },
  {
   "title": "stEth currentStrategyTVL (unit 1e18)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_stEthDeposits\n{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "deposits"
    },
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_stEthPendingWithdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "pendingWithdrawals"
    },
    {
     "expr": "preprodGraphScraper_currentStrategyTVL_stEthWithdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "withdrawals"
    }
   ]
  },
  {
   "title": "eigenPodWithdrawalBuckets unit 1e18",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "preprodGraphScraper_eigenPodWithdrawalBuckets_pendingWithdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "pendingWithdrawals"
    },
    {
     "expr": "preprodGraphScraper_eigenPodWithdrawalBuckets_withdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"}  / 1e18",
     "legendFormat": "withdrawals"
    }
   ]
  },
  {
   "title": "Are we having trouble? (no data here = good)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 } },
  {
   "title": "K8s Pods Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "(Sentry) Frontend Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
   "targets": [
    {
     "issuesQuery": "GrafanaFeed:\"NetworkError\"",
     "issuesSort": "date",
     "projectIds": [ "4504923624833025" ],
     "statsCategory": [ "transaction" ],
     "statsFields": [ "sum(times_seen)" ],
     "statsGroupBy": [ "category" ]
    }
   ]
  },
  {
   "title": "# of Eigenpods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"data.variable.integerValue\"",
     "url": "https://bfyivmn2gj.execute-api.us-east-2.amazonaws.com/goerli/graph-internal",
     "url_options": {
      "body_content_type": "text/plain",
      "body_graphql_query": "{\n  variable(id: \"podCount\") {\n    id\n    integerValue\n  }\n}",
      "body_type": "graphql",
      "data": "{\n  variable(id: \"podCount\") {\n    id\n    integerValue\n  }\n}",
      "headers": [],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Oncall alert debug",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "options": {
    "content": "###How to see the alert rule and plot that generates the oncall slack alert\nhttps://app.gitbook.com/o/bJhVFeKDe5jNBwSZCd4B/s/ohvKF4REMMk6Jl2iD2wL/what-to-do-after-seeing-oncall-slack-alert\n\n###Alert Conditions:\nhttps://docs.google.com/spreadsheets/d/1be3gcOs1ym5fk5lO2mWQEDbI8zSxu9zy3gXCsjAjHQw/edit#gid=0\n"
   }
  },
  {
   "title": "chaind sync distance (epochs)",
   "type": "gauge",
   "description": "number of epochs chaind is behind lighthouse clients",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$chaind_head_epoch - $lighthouse_head_epoch",
     "type": "math"
    }
   ]
  },
  {
   "title": "lighthouse-0 sync distance (slot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse_0 - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "lighthouse-1 sync distance (slot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "lighthouse-2 sync distance (slot)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "thegraph sync distance (blocks)",
   "type": "gauge",
   "description": "number of slots thegraph is behind nethermind clients",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$thegraph_head - $nethermind_head",
     "type": "math"
    }
   ]
  },
  {
   "title": "nethermin-0 sync distance (block)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$lighthouse - $beaconchain", "type": "math" }
   ]
  },
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "options": {
    "content": "Can't get the EL sync distance to show. Check https://eigenlayer.grafana.net/d/ZbOKkYBVk/general-monitoring-dashboard-for-m1?orgId=1&refresh=10s&from=1680568307926&to=1680571907926&viewPanel=18"
   }
  },
  {
   "title": "API Gateway traffic (main backend entrypoint)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Total Requests ($__interval)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "5XXError",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Stage": "$apigateway_stage" },
     "id": "e500",
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Stage": "$apigateway_stage" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "V1 p50 Duration (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": {
      "ApiName": "$api_name",
      "Method": "GET",
      "Resource": "/restaking/v1/pod/{address}/summary",
      "Stage": "$apigateway_stage"
     },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p50"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p50"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Resource": "/price", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p50"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "options": {
    "content": "- Routes\n  - /price: cached proxy to coingecko\n  - /graph-internal: retrieves information from the graph node for the frontend\n  - /restaking/pods/{address}/summary: calls the lambda to get solo staker information"
   }
  },
  {
   "title": "Total Requests per route ($__interval)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Stage": "$apigateway_stage" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Stage": "$apigateway_stage" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "4XXError",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Stage": "$apigateway_stage" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Stage": "$apigateway_stage" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "V1 p90 (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Method": "GET", "Resource": "/price", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Resource": "/graph-internal", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    },
    {
     "dimensions": {
      "ApiName": "$api_name",
      "Method": "GET",
      "Resource": "/restaking/v1/pod/{address}/summary",
      "Stage": "$apigateway_stage"
     },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Method": "POST", "Resource": "/graph", "Stage": "$apigateway_stage" },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    }
   ]
  },
  {
   "title": "Lambda RED (Requests, Errors, Duration) - load-test 1req/min traffic always present",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Lambda # Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "dimensions": {
      "Resource": "eigenlayer-pp-usea2-goerli-rewards-v1:stable-alias"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "Resource": "eigenlayer-pp-usea2-goerli-rewards-v2"
     },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Invocation Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "dimensions": {
      "Resource": "eigenlayer-pp-usea2-goerli-rewards-v1:stable-alias"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "Resource": "eigenlayer-pp-usea2-goerli-rewards-v2"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "dimensions": {
      "Resource": "eigenlayer-pp-usea2-goerli-rewards-v1:stable-alias"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "Resource": "eigenlayer-pp-usea2-goerli-rewards-v2"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Elasticache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Cache Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "metricName": "CacheHits",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "CacheMisses",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "Evictions",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "metricName": "Reclaimed",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Kubernetes Instances + Pods (CPU, memory, storage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Node/Instance Level Resource Usage",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "options": {
    "content": "- (public subnet) clel nodegroup\n  - runs CL (lighthouse) + EL (nethermind) clients\n- (private subnet) default nodegroup\n  - runs CL (chaind) and EL (thegraph) indexers\n\nNote: Spike traffic is explained by chaind writing at epoch boundaries (~ every 6 mins)\n\nTODO: relabel the instances with subnet info so that we can compare indexing vs query work. We might even want to duplicate every dashboard, since we'll likely mostly be interested in the private subnet serving read requests."
   }
  },
  {
   "title": "Pod Level Resource Usage",
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 56 },
   "options": {
    "content": "- clients\n  - (consensus) lighthouse x3\n  - (execution) nethermind x3\n- indexers\n  - (execution) thegraph\n    - query nodes          x3\n    - indexer              x1\n    - ipfs                 x1\n  - (consensus) chaind     x1"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 56 },
   "options": {
    "content": "Note: it's normal for nethermind client to use >20G of RAM "
   }
  },
  {
   "title": "$cluster System CPU percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cluster, node) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) / sum by(cluster, node) (kube_node_status_capacity{resource=\"cpu\", cluster=~\"$cluster\"}) ",
     "legendFormat": "{{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "$cluster ($namespace namespaces) Pod vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum  (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cluster, node) (node_namespace_pod_container:container_memory_working_set_bytes{}) / sum by(cluster, node) (kube_node_status_capacity{resource=\"memory\", cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}/{{node}}"
    }
   ]
  },
  {
   "title": "$cluster/$namespace Pod Memory WSS (32G/private-node, 8G/public-node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", namespace=~\"$namespace\", container!=\"\", image!=\"\", cluster=~\"$cluster\"}) by (pod) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster/$namespace Persistent Volume %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n(kubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"$namespace\", cluster=~\"$cluster\"} -\nkubelet_volume_stats_available_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) / \nkubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients, graph, chaind head sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }
  },
  {
   "title": "beaconcha.in head epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"data.epoch\"",
     "url": "https://goerli.beaconcha.in/api/v1/slot/latest?apikey=$beaconchain_apikey",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "beaconcha.in head slot",
   "type": "stat",
   "description": "head block of execution client",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"data.slot\" ",
     "url": "https://goerli.beaconcha.in/api/v1/slot/latest?apikey=$beaconchain_apikey",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": []
     }
    }
   ]
  },
  {
   "title": "infura head block",
   "type": "stat",
   "description": "head slot of execution client",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "json_options": {
      "root_is_not_array": false
     },
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| jsonata \"result\"",
     "url": "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "CL head epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CL head epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slotclock_present_slot{cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "EL clients head block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks{cluster=~\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chaind head epoch",
   "type": "stat",
   "description": "Last chaind processed slot",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chaind_validators_latest_epoch{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 100 },
   "options": {
    "content": "TODO: --->\nfix the thegraph panel to only show the running instance\n\n<--- TODO --->:\nGeneral issue with restarting leaves a duplicate"
   }
  },
  {
   "title": "The Graph head",
   "type": "stat",
   "description": "last thegraph processed block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_head{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}, {{ deployment }}"
    }
   ]
  },
  {
   "title": "strategyTVLBuckets (unit 1e18)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 108 },
   "targets": [
    {
     "expr": "preprodGraphScraper_strategyTVLBuckets_deposits{namespace=\"graph-scraper\", cluster=\"$cluster\"}  / 1e18",
     "legendFormat": "deposits"
    },
    {
     "expr": "preprodGraphScraper_strategyTVLBuckets_pendingWithdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"}  / 1e18",
     "legendFormat": "pendingWithdrawals"
    },
    {
     "expr": "preprodGraphScraper_strategyTVLBuckets_withdrawals{namespace=\"graph-scraper\", cluster=\"$cluster\"} / 1e18",
     "legendFormat": "withdrawals"
    }
   ]
  }
 ]
}