{
 "title": "Graph",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Chain", "label": "chain", "query": "devnet, goerli, mainnet" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"integrations/kubernetes/kube-state-metrics\"},cluster)"
    }
   },
   { "name": "namespace", "label": "namespace", "query": "graph" },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(deployment_block_processing_duration_bucket{cluster=\"$cluster\"}, deployment)"
    }
   },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "$cluster/$namespace Pod vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum  (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster/$namespace Pod Memory WSS (16G per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", namespace=~\"$namespace\", image!=\"\", cluster=~\"$cluster\"}) by (pod) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$cluster/$namespace Pod RX bandwidth",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 }
  },
  {
   "title": "$cluster/$namespace Pod TX bandwidth",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 }
  },
  {
   "title": "$cluster/$namespace Persistent Volume %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 }
  },
  { "title": "$cluster Container restarts", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 } },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Number of processed blocks (per 10 mins)",
   "type": "timeseries",
   "description": "The amount of block processed by a subgraph deployment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "targets": [
    {
     "expr": "sum(increase(deployment_block_processing_duration_count{deployment=~\"$deployment\", cluster=~\"$cluster\", job=~\"$job\"}[10m])) by (deployment, cluster, job)",
     "legendFormat": "{{pod}}/{{deployment}}"
    }
   ]
  },
  {
   "title": "Average block processing time ($__interval)",
   "type": "timeseries",
   "description": "The average block processing time for a subgraph deployment",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(deployment_block_processing_duration_sum{cluster=~\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (deployment, pod) / avg(rate(deployment_block_processing_duration_count{cluster=~\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (deployment, pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total triggers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "deployment_block_trigger_count_sum{cluster=~\"$cluster\", job=~\"$job\"}",
     "legendFormat": "{{pod}}/{{deployment}}"
    }
   ]
  },
  {
   "title": "Rate of triggers ($__interval)",
   "type": "timeseries",
   "description": "Rate of triggers in each block over a 5 minute period for the subgraph deployment.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "avg(rate(deployment_block_trigger_count_sum{cluster=~\"$cluster\", job=~\"$job\"}[$__rate_interval])) by (deployment, pod)",
     "legendFormat": "{{pod}}/{{deployment}}"
    }
   ]
  },
  {
   "title": "95th and 99th Percentile Triggers per Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (deployment_block_trigger_count_bucket{cluster=~\"$cluster\", deployment=~\"$deployment\", job=~\"$job\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (deployment_block_trigger_count_bucket{cluster=~\"$cluster\", deployment=~\"$deployment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Triggers per Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(deployment_block_trigger_count_sum{cluster=~\"$cluster\", deployment=~\"$deployment\", job=~\"$job\"}) by (deployment, pod) / sum(deployment_block_trigger_count_count{cluster=~\"$cluster\", deployment=~\"$deployment\", job=~\"$job\"}) by (deployment, pod)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average handler execution time",
   "type": "timeseries",
   "description": "Average execution time of each handler over a 5 minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(deployment_handler_execution_time_sum{cluster=~\"$cluster\", job=~\"$job\"}[5m])) by (handler) / avg(rate(deployment_handler_execution_time_count{cluster=~\"$cluster\", job=~\"$job\"}[5m])) by (handler)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Block Trigger Count Increase by Bucket ($__interval)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(increase(deployment_block_trigger_count_bucket{cluster=~\"$cluster\", deployment=~\"$deployment\", job=~\"$job\"}[$__interval])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Graph Query pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\", namespace=\"graph\", pod=~\"graph-query-.*\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries processed",
   "type": "timeseries",
   "description": "Size of the result of successful GraphQL queries (in CacheWeight)\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(query_result_size_bucket{le=\"+Inf\", container=\"graph-query\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Result Size per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(query_result_size_sum{cluster=~\"$cluster\"}) by (pod) / sum(query_result_size_count{cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Result Size Rate per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(query_result_size_sum{cluster=~\"$cluster\", container=\"graph-query\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache performance",
   "type": "timeseries",
   "description": "Measures percentage of hits to the cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(query_cache_status_count{cache_status=\"hit\", cluster=~\"$cluster\"}[5m])) \n/ \nsum(rate(query_cache_status_count{cluster=~\"$cluster\"}[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Status Breakdown",
   "type": "timeseries",
   "description": "Shows the average number of cache hits, misses, inserts, and shared status.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "avg(rate(query_cache_status_count{cluster=~\"$cluster\", cache_status=~\"hit|miss|insert|shared\"}[5m])) by (cache_status)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Checked-out connections",
   "type": "timeseries",
   "description": "Sum of checked-out connections per pool and shard",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(store_connection_checkout_count{pool=~\"main|replica1\",shard=\"primary\", cluster=~\"$cluster\"}) by (pool, shard, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection errors",
   "type": "timeseries",
   "description": "Rate of connection errors per pool and shard over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "sum(rate(store_connection_error_count{pool=~\"main|replica1\",shard=\"primary\", cluster=~\"$cluster\"}[5m])) by (pool, shard, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection pool size",
   "type": "timeseries",
   "description": "Sum of connection pool sizes per pool and shard.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(store_connection_pool_size_count{pool=~\"main|replica1\",shard=\"primary\", cluster=~\"$cluster\"}) by (pool, shard, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average connection wait time",
   "type": "timeseries",
   "description": "Average of wait times per pool and shard",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(store_connection_wait_time_ms{pool=~\"main|replica1\",shard=\"primary\", cluster=~\"$cluster\"}) by (pool, shard, job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}