{
 "title": "Ops",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Alert list", "type": "alertlist", "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "Event",
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "options": {
    "content": "System update happens on Jan 12 2023 which recreated the following clusters\n* devnet-chain: running chain \n* frontend: running eigenda\n* devnet-a: eigenda rollup testnet\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "System CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(cluster, node) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) / sum by(cluster, node) (kube_node_status_capacity{resource=\"cpu\"}) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "System memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(cluster, node) (node_namespace_pod_container:container_memory_working_set_bytes{}) / sum by(cluster, node) (kube_node_status_capacity{resource=\"memory\"}) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Devnet-a cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Dispersal Success %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(increase(dl_disperser_request{type=\"number\", outcome=\"success\"}[2m])) /  ignoring(outcome)  sum without(outcome) (increase(dl_disperser_request{type=\"number\"}[2m])) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Aggregated Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(app) (rate(dl_disperser_size_success_traffic[10m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devnet-a Pod vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum  (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"default|relay\", cluster=\"devnet-a\"}) by (pod) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devnet-a Pod Memory WSS (16G per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", container!=\"\", image!=\"\", cluster=\"devnet-a\"}) by (pod) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devnet-a Pod RX bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", cluster=\"devnet-a\"}[$__rate_interval])) by (pod) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod TX bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", cluster=\"devnet-a\"}[$__rate_interval])) by (pod) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devnet-a Persistent Volume %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n(kubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-a\"} -\nkubelet_volume_stats_available_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-a\"}) / \nkubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-a\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Devnet Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=~\"devnet-a\", namespace=\"default\"}[1h])"
    }
   ]
  },
  { "title": "Frontend cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Frontend Pod vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum  (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"default|relay\", cluster=\"devnet-frontend\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Pod Memory WSS (16G per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", container!=\"\", image!=\"\", cluster=\"devnet-frontend\"}) by (pod) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod RX bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", cluster=\"devnet-frontend\"}[$__rate_interval])) by (pod) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod TX bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", cluster=\"devnet-frontend\"}[$__rate_interval])) by (pod) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Persistent Volume %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n(kubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-frontend\"} -\nkubelet_volume_stats_available_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-frontend\"}) / \nkubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-frontend\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"devnet-frontend\", namespace=\"default\"}[1h])"
    }
   ]
  },
  { "title": "Chain cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Chain Pod vCPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum  (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"default|relay\", cluster=\"devnet-chain\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Pod Memory WSS (16G per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", container!=\"\", image!=\"\", cluster=\"devnet-chain\"}) by (pod) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod RX bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", cluster=\"devnet-chain\"}[$__rate_interval])) by (pod) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pod TX bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"integrations/kubernetes/cadvisor\", namespace=~\"default|relay\", cluster=\"devnet-chain\"}[$__rate_interval])) by (pod) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Persistent Volume %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n(kubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-chain\"} -\nkubelet_volume_stats_available_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-chain\"}) / \nkubelet_volume_stats_capacity_bytes{job=\"integrations/kubernetes/kubelet\", namespace=~\"default|relay\", cluster=\"devnet-chain\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"devnet-chain\", namespace=~\"default|relay\"}[$__rate_interval])"
    }
   ]
  }
 ]
}