{
 "title": "Lighthouse Sync",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(sync_peers_per_status, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_finalized_epoch",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Peers per sync status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_peers_per_status{cluster=~\"$cluster\"}",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Syncing chain counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_range_chains{cluster=~\"$cluster\"}",
     "legendFormat": "{{range_type}}"
    }
   ]
  },
  {
   "title": "Lighthouse Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_loadavg_1", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Sync slots per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_slots_per_second{cluster=~\"$cluster\"}",
     "legendFormat": " "
    }
   ]
  }
 ]
}