{
 "title": "Lighthouse Networking",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "Fork", "query": { "query": "label_values(hash)" } },
   { "name": "Topic", "query": { "query": "label_values(hash)" } }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers{instance=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NAT",
   "type": "stat",
   "description": "Is the UDP port forwarded",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "nat_open{instance=~\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Blocks Per Slot",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=~\".*beacon_block.*\", instance=~\"$Instance\"}[$__rate_interval])*12"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "piechart",
   "description": "Peers via client implementations",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_peers_per_client{instance=~\"$Instance\"}",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Peer Type",
   "type": "piechart",
   "description": "Peers that have dialed us",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_inbound_peers{instance=~\"$Instance\"}",
     "legendFormat": "Inbound"
    },
    {
     "expr": "network_outbound_peers{instance=~\"$Instance\"}",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Total Libp2p Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_bandwidth{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Libp2p Inbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_inbound_bytes{instance=~\"$Instance\"}[1m])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Libp2p Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_outbound_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Average Peer Score Per Client",
   "type": "piechart",
   "description": "Average Peer score per client shifted by 100",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peer_score_per_client{instance=~\"$Instance\"}+100",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Peer Sync Status",
   "type": "piechart",
   "description": "Peers sync status",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sync_peers_per_status{instance=~\"$Instance\"}",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_bandwidth{instance=~\"$Instance\"}[$__rate_interval]) + rate(discovery_sent_bytes{instance=~\"$Instance\"}[$__rate_interval]) + rate(discovery_recv_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} bytes/s"
    }
   ]
  },
  {
   "title": "Discovery Inbound Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_recv_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Discovery Outbound Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(discovery_sent_bytes{instance=~\"$Instance\"}[$__rate_interval])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Peer Penalty Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "increase(libp2p_report_peer_msgs_total{instance=~\"$Instance\"}[1m])",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Unsolicited Discovery Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "discovery_requests{instance=~\"$Instance\"}",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Active Discv5 Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "discovery_sessions{instance=~\"$Instance\"}",
     "legendFormat": "active sessions"
    }
   ]
  },
  {
   "title": "Queued Discovery Queries",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "discovery_queue_size{instance=~\"$Instance\"}",
     "legendFormat": "Queued Discoveries"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Peer Score Distribution",
     "type": "timeseries",
     "description": "Distribution of connected peer's score by quartile",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "peer_score_distribution{instance=~\"$Instance\"}",
       "legendFormat": "{{position}}"
      }
     ]
    },
    {
     "title": "RPC Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum(rate(libp2p_rpc_errors_per_client{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "Errors Per Second"
      }
     ]
    },
    {
     "title": "RPC Errors (Non timeout)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "rate(libp2p_rpc_errors_per_client{rpc_error!~\"timeout\", instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{client}} - {{rpc_error}}"
      }
     ]
    },
    {
     "title": "10m Average RPC Requests per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 39 },
     "targets": [
      {
       "expr": "rate(libp2p_rpc_requests_total{instance=~\"$Instance\"}[10m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "RPC Timeouts Per Client",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "rate(libp2p_rpc_errors_per_client{rpc_error=~\"negotiation_timeout|stream_timeout\", instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{client}} -{{rpc_error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossipsub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mesh Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "gossipsub_mesh_peer_counts{hash=~\".*$Topic.*\", instance=~\"$Instance\"}",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Blocks Per Slot",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=~\".*beacon_block.*\", instance=~\"$Instance\"}[$__rate_interval])*12"
      }
     ]
    },
    {
     "title": "Aggregated Attestations Per Slot",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(gossipsub_topic_msg_recv_counts_total{hash=~\".*beacon_aggregate_and_proof.*\", instance=~\"$Instance\"}[$__rate_interval])*12"
      }
     ]
    },
    {
     "title": "Invalid Messages Per Slot",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(gossipsub_invalid_messages_per_topic{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Cache Misses",
     "type": "gauge",
     "description": "Cache Misses over a 10m window",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(gossipsub_memcache_misses_total{instance=~\"$Instance\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Aggregate and Proof Peer Score",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(gossipsub_score_per_mesh_bucket{hash=~\".*beacon_aggregate_and_proof.*\", instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "10m Average of Block Delay from Start of Slot",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(beacon_block_gossip_slot_start_delay_time_bucket{instance=~\"$Instance\"}[10m])*12",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "30s Block Delay Average",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(beacon_block_gossip_slot_start_delay_time_sum{instance=~\"$Instance\"}[30s])/rate(beacon_block_gossip_slot_start_delay_time_count{instance=~\"$Instance\"}[30s])",
       "legendFormat": "Block Delay"
      }
     ]
    },
    {
     "title": "IWANT Requests Per Slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "increase(gossipsub_topic_iwant_msgs_total{instance=~\"$Instance\", hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\"}[12s])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Duplicates Filtered Per Slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "rate(gossipsub_topic_msg_recv_counts_unfiltered_total{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}[$__rate_interval])*12 - rate(gossipsub_topic_msg_recv_counts_total{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}[$__rate_interval])*12",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Attestation Errors Per Slot",
     "type": "timeseries",
     "description": "Gossipsub Attestation Errors By Type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "changes(gossipsub_attestation_errors_per_type[$__interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Gossip Penalties Per Slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "rate(gossipsub_scoring_penalties_total{instance=~\"$Instance\"}[$__rate_interval])*12",
       "legendFormat": "{{penalty}}"
      }
     ]
    },
    {
     "title": "Heartbeat Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(rate(gossipsub_heartbeat_duration_sum{instance=~\"$Instance\"}[$__rate_interval]))/sum(rate(gossipsub_heartbeat_duration_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{Instance}}"
      }
     ]
    },
    {
     "title": "Memcache Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "gossipsub_memcache_size{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Subscribed Topics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "count by(instance) (gossipsub_topic_subscription_status{hash=~\"/eth2/$Fork/.*\", instance=~\"$Instance\"} == 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Subscribed AttNets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "count by(instance) (gossipsub_topic_subscription_status{hash=~\"/eth2/$Fork/beacon_attestation.*\", instance=~\"$Instance\"} == 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Sent Message Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "gossipsub_topic_msg_last_sent_bytes{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Last Recv Message Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "gossipsub_topic_msg_last_recv_bytes{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Recv Message Counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 1, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "changes(gossipsub_topic_msg_recv_counts_total{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}[$__interval])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Last Recv Message Bytes Unfiltered",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "gossipsub_topic_msg_last_recv_bytes_unfiltered{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Sent Bytes per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(gossipsub_topic_msg_sent_bytes_total{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Recv Bytes per Topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(gossipsub_topic_msg_recv_bytes_total{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Accepted Messages Per Slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "changes(gossipsub_accepted_messages_per_topic_total{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\", instance=~\"$Instance\"}[$__interval])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Mesh Inclusions - Beacon Block",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "changes(gossipsub_mesh_peer_inclusion_events_total{hash=~\"/eth2/$Fork/beacon_block.*\", instance=~\"$Instance\"}[$__interval])",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Mesh Inclusions - Beacon Block",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "changes(gossipsub_mesh_peer_inclusion_events_total{hash=~\"/eth2/$Fork/beacon_aggregate_and_proof.*\", instance=~\"$Instance\"}[$__interval])",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Mesh Removals - Beacon Block",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "changes(gossipsub_mesh_peer_churn_events_total{hash=~\"/eth2/$Fork/beacon_block.*\", instance=~\"$Instance\"}[$__interval])",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Mesh Removals - Aggregate and Proof",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "changes(gossipsub_mesh_peer_churn_events_total{hash=~\"/eth2/$Fork/beacon_aggregate_and_proof.*\", instance=~\"$Instance\"}[$__interval])",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Ignored Messages Per Slot",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(gossipsub_ignored_messages_per_topic_total{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\",instance=~\"$Instance\"}[$__rate_interval])*12",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Gossipsub Ignored Messages Per Client per Slot",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(gossipsub_unaccepted_messages_per_client{instance=~\"$Instance\"}[$__rate_interval])*12",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "BeaconBlock Mesh Peers",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "block_mesh_peers_per_client{instance=~\"$Instance\"}",
       "legendFormat": "{{Client}}"
      }
     ]
    },
    {
     "title": "BeaconAggregateAndProof Mesh Peers",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "beacon_aggregate_and_proof_mesh_peers_per_client{instance=~\"$Instance\"}",
       "legendFormat": "{{Client}}"
      }
     ]
    },
    {
     "title": "Subscribed Peers Per Topic",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 5, "y": 121 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gossipsub_topic_peers_counts{hash!~\".*attester_slashing.*|.*beacon_aggregate_and_proof.*|.*beacon_block.*|.*proposer_slashing.*|.*voluntary_exit.*|.*sync_committee_contribution_and_proof.*\", hash=~\"/eth2/$Fork/.*\", instance=~\"$Instance\"}",
       "legendFormat": "{{hash}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Episub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Choked Peers In Mesh",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "gossipsub_episub_current_choked_peers_in_mesh{instance=~\"$Instance\", hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\"}",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Peers added to mesh via Episub",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "changes(gossipsub_episub_mesh_additions_total{instance=~\"$Instance\", hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\"}[$__interval])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Peers that have Choked us",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "gossipsub_episub_current_peers_choked_us{instance=~\"$Instance\", hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\"}",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Choked messages received/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "rate(gossipsub_episub_received_choke_messages{instance=~\"$Instance\", hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\"}[$__rate_interval])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "UnChoke messages received/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "rate(gossipsub_episub_received_unchoke_messages{instance=~\"$Instance\", hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\"}[$__rate_interval])",
       "legendFormat": "{{hash}}"
      }
     ]
    },
    {
     "title": "Episub Heartbeat Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(gossipsub_episub_heartbeat_duration_sum{instance=~\"$Instance\"}[$__rate_interval]))/sum(rate(gossipsub_heartbeat_duration_count{instance=~\"$Instance\"}[$__rate_interval]))",
       "legendFormat": "{{Instance}}"
      }
     ]
    },
    {
     "title": "Episub Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "gossipsub_episub_metrics_cache_size{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Episub IHAVE Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "gossipsub_episub_metrics_ihave_cache_size{instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Message Latency - Beacon Block",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(increase(gossipsub_episub_mesh_message_latency_bucket{hash=~\".*beacon_block.*\",instance=~\"$Instance\"}[20s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Message Latency - Aggregate and Proof",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum(increase(gossipsub_episub_mesh_message_latency_bucket{hash=~\".*beacon_aggregate_and_proof.*\",instance=~\"$Instance\"}[20s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Message Latency - Custom",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum(increase(gossipsub_episub_mesh_message_latency_bucket{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\",instance=~\"$Instance\"}[20s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IHAVE percent before message - Custom",
     "type": "heatmap",
     "description": "The percentage of messages that we received an IHAVE before the we received the actual message",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "sum(increase(gossipsub_episub_ihave_message_stats_bucket{hash=~\"/eth2/$Fork/.*\", hash=~\".*$Topic.*\",instance=~\"$Instance\"}[20s])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}