{
 "title": "Nethermind",
 "tags": [
  "eth1.0",
  "ethereum",
  "nethermind"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(nethermind_version{}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nethermind_version{}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(nethermind_version{}, pod)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nethermind_version{}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_sync_peers{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Connections (per minute)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nethermind_incoming_connections{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Incoming Connections"
    },
    {
     "expr": "rate(nethermind_outgoing_connections{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Outgoing Connections"
    },
    {
     "expr": "rate(nethermind_handshakes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Handshakes"
    },
    {
     "expr": "rate(nethermind_hellos_sent{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Hellos Sent"
    },
    {
     "expr": "rate(nethermind_hellos_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Hellos Received"
    },
    {
     "expr": "rate(nethermind_statuses_sent{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Statuses Sent"
    },
    {
     "expr": "rate(nethermind_statuses_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Statuses Received"
    }
   ]
  },
  {
   "title": "Pending Txs (per minute)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nethermind_pending_transactions_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(nethermind_pending_transactions_known{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Already Known"
    },
    {
     "expr": "rate(nethermind_pending_transactions_discarded{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Discarded"
    },
    {
     "expr": "rate(nethermind_pending_transactions_too_far_in_future{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Too far in future"
    },
    {
     "expr": "rate(nethermind_pending_transactions_too_low_fee{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Too low fee"
    },
    {
     "expr": "rate(nethermind_pending_transactions_added{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Added (all)"
    },
    {
     "expr": "rate(nethermind_pending1559transactions_added{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Added (1559)"
    },
    {
     "expr": "rate(nethermind_pending_transactions_evicted{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Evicted"
    },
    {
     "expr": "rate(nethermind_pending_transactions_sent{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Sent txs"
    },
    {
     "expr": "rate(nethermind_pending_transactions_hashes_sent{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Sent hashes"
    }
   ]
  },
  {
   "title": "Disconnects (per minute)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nethermind_too_many_peers_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Too Many Peers"
    },
    {
     "expr": "rate(nethermind_client_quitting_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Client Quitting"
    },
    {
     "expr": "rate(nethermind_receive_message_timeout_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Receive Timeouts"
    },
    {
     "expr": "rate(nethermind_already_connected_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Already Connected"
    },
    {
     "expr": "rate(nethermind_breach_of_protocol_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Breach of Protocol"
    },
    {
     "expr": "rate(nethermind_incompatible_p2pdisconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Incompatible P2P"
    },
    {
     "expr": "rate(nethermind_null_node_identity_disconnects{job=\"nethermind\",_instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Null Identity"
    },
    {
     "expr": "rate(nethermind_unexpected_identity_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Unexpected Identity"
    },
    {
     "expr": "rate(nethermind_useless_peer_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Useless Peer"
    },
    {
     "expr": "rate(nethermind_diconnect_requested_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Requested"
    },
    {
     "expr": "rate(nethermind_tcp_subsystem_error_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "TCP Error"
    },
    {
     "expr": "rate(nethermind_same_as_self_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Same as Self"
    },
    {
     "expr": "rate(nethermind_other_disconnects{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Eth62, Eth63, Eth65, Eth66 (per minute)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nethermind_eth62get_block_headers_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetBlockHeaders eth62"
    },
    {
     "expr": "rate(nethermind_eth62block_headers_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "BlockHeaders eth62"
    },
    {
     "expr": "rate(nethermind_eth62get_block_bodies_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetBlockBodies eth62"
    },
    {
     "expr": "rate(nethermind_eth62block_bodies_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "BlockBodies eth62"
    },
    {
     "expr": "rate(nethermind_eth62transactions_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Txs received eth62"
    },
    {
     "expr": "rate(nethermind_eth65get_pooled_transactions_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Txs requests received eth65"
    },
    {
     "expr": "rate(nethermind_eth65get_pooled_transactions_requested{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Txs requested eth65"
    },
    {
     "expr": "rate(nethermind_eth65pooled_transactions_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Txs received eth65"
    },
    {
     "expr": "rate(nethermind_eth62new_block_hashes_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "NewBlockHashes eth62"
    },
    {
     "expr": "rate(nethermind_eth62new_block_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "NewBlock eth62"
    },
    {
     "expr": "rate(nethermind_eth63get_node_data_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetNodeData eth63"
    },
    {
     "expr": "rate(nethermind_eth63node_data_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "NodeData eth63"
    },
    {
     "expr": "rate(nethermind_eth63get_receipts_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetReceipts eth63"
    },
    {
     "expr": "rate(nethermind_eth63receipts_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Receipts eth63"
    },
    {
     "expr": "rate(nethermind_eth66get_block_headers_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetBlockHeaders eth66"
    },
    {
     "expr": "rate(nethermind_eth66block_headers_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "BlockHeaders eth66"
    },
    {
     "expr": "rate(nethermind_eth66get_block_bodies_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetBlockBodies eth66"
    },
    {
     "expr": "rate(nethermind_eth66block_bodies_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "BlockBodies eth66"
    },
    {
     "expr": "rate(nethermind_eth66get_pooled_transactions_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Txs requests received eth66"
    },
    {
     "expr": "rate(nethermind_eth66get_pooled_transactions_requested{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Txs requested eth66"
    },
    {
     "expr": "rate(nethermind_eth66pooled_transactions_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Txs received eth66"
    },
    {
     "expr": "rate(nethermind_eth66get_node_data_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetNodeData eth66"
    },
    {
     "expr": "rate(nethermind_eth66node_data_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "NodeData eth66"
    },
    {
     "expr": "rate(nethermind_eth66get_receipts_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "GetReceipts eth66"
    },
    {
     "expr": "rate(nethermind_eth66receipts_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Receipts eth66"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_json_rpc_bytes_sent{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "RPC Sent"
    },
    {
     "expr": "rate(nethermind_json_rpc_bytes_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "RPC Received"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Dscv Sent"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_sent{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Dscv Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_received{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "P2P Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_sent{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "P2P Sent"
    }
   ]
  },
  {
   "title": "Blocks Sealed (total)",
   "type": "stat",
   "description": "Total number of sealed blocks",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks_sealed{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Block Seals (total)",
   "type": "stat",
   "description": "Total number of failed block seals",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_failed_block_seals{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Reported Benign Misbehaviour",
   "type": "stat",
   "description": "Number of reported benign misbehaviour validators",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_reported_benign_misbehaviour{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Blocks Production Indicator",
   "type": "stat",
   "description": "Indicator if blocks can be produced",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_can_produce_blocks{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Reported Malicious Misbehaviour",
   "type": "stat",
   "description": "Number of reported malicious misbehaviour validators",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_reported_malicious_misbehaviour{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Validators Count",
   "type": "stat",
   "description": "Number of current AuRa validators",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_validators_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sync Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_sync_peers{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Sync Peers"
    }
   ]
  },
  {
   "title": "Block processing time (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_last_block_processing_time_in_ms{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocks (per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_blocks{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "State Synced (in bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nethermind_state_synced{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "State"
    },
    {
     "expr": "rate(nethermind_state_synced{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[60m])*3600"
    }
   ]
  },
  {
   "title": "Fast Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_fast_headers{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "Headers"
    },
    {
     "expr": "nethermind_fast_bodies{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "Bodies"
    },
    {
     "expr": "nethermind_fast_receipts{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "Receipts"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_blocks{cluster=~\"$cluster\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU time (tracks restarts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "JSON RPC (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_json_rpc_successes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "RPC Successes"
    },
    {
     "expr": "rate(nethermind_json_rpc_errors{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "RPC Errors"
    },
    {
     "expr": "rate(nethermind_json_rpc_request_deserialization_failures{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Deserialization Failures"
    },
    {
     "expr": "rate(nethermind_json_rpc_invalid_requests{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  {
   "title": "JSON RPC (total)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nethermind_json_rpc_requests{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "RPC Requests"
    },
    {
     "expr": "nethermind_json_rpc_successes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "RPC Successes"
    },
    {
     "expr": "nethermind_json_rpc_errors{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "RPC Errors"
    },
    {
     "expr": "nethermind_json_rpc_request_deserialization_failures{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "Deserialization Failures"
    },
    {
     "expr": "nethermind_json_rpc_invalid_requests{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  {
   "title": "AuRa Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "POSDAO Emit Initiate Change",
     "type": "graph",
     "description": "POSDAO number of emit init change transactions",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_emit_initiate_change{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Aura Step",
     "type": "graph",
     "description": "Current AuRa step",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_au_ra_step{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "RANDAO Reveal Number",
     "type": "graph",
     "description": "RANDAO number of reveal number transactions",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_reveal_number{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Sealed Transactions",
     "type": "graph",
     "description": "Number of sealed transactions generated by engine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_sealed_transactions{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "RANDAO Commit Hash Transaction",
     "type": "graph",
     "description": "RANDAO number of commit hash transactions",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_commit_hash_transaction{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Managed Memory"
      },
      {
       "expr": " process_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Unmanaged Memory"
      }
     ]
    },
    {
     "title": "Memory Growth (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "deriv(dotnet_total_memory_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m]) > 0",
       "legendFormat": "Managed Memory",
       "target": "*.Nethermind_Runner.*.*.*.*.gauge.*.Process_Physical_Memory"
      }
     ]
    },
    {
     "title": "GC (per minute)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"0\",namespace=\"$namespace\",pod=\"$pod\"}[1m])*60",
       "legendFormat": "Gen 0"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"1\",namespace=\"$namespace\",pod=\"$pod\"}[1m])*60",
       "legendFormat": "Gen 1"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"2\",namespace=\"$namespace\",pod=\"$pod\"}[1m])*60",
       "legendFormat": "Gen 2"
      }
     ]
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Caching Efficiency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_loaded_from_db_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "DB"
      },
      {
       "expr": "nethermind_loaded_from_rlp_cache_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "RLP Cache"
      },
      {
       "expr": "nethermind_loaded_from_cache_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Node Cache"
      },
      {}
     ]
    },
    {
     "title": "Pruning Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nethermind_memory_used_by_cache{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Pruning Levels",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_committed_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "nethermind_persisted_node_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Persisted"
      },
      {
       "expr": "nethermind_cached_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "nethermind_replaced_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Replaced"
      },
      {
       "expr": "nethermind_pruned_persisted_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Pruned Persisted"
      },
      {
       "expr": "nethermind_pruned_transient_nodes_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Pruned Transient"
      }
     ]
    },
    {
     "title": "Times",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_snapshot_persistence_time{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Persistence"
      },
      {
       "expr": "nethermind_pruning_time{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Pruning"
      },
      {
       "expr": "nethermind_deep_pruning_time{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beam",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Beamed Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_beamed_transactions{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Transactions"
      }
     ]
    },
    {
     "title": "Beamed Blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_beamed_blocks{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Beamed Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_beamed_requests{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "Beamed Trie Nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_beamed_trie_nodes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Trie Nodes"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receipts DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_receipts_db_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[10s])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_receipts_db_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[10s])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Code DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_code_db_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_code_db_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "State Tree",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_state_tree_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_state_tree_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Block Info DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_block_infos_db_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_block_infos_db_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "State DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_state_db_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_state_db_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Writes"
      },
      {
       "expr": "rate(nethermind_state_db_in_pruning_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Pruning Writes"
      }
     ]
    },
    {
     "title": "Storage Tree",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_storage_tree_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_storage_tree_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Trie Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_tree_node_rlp_decodings{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "RLP.Encode"
      },
      {
       "expr": "rate(nethermind_tree_node_rlp_encodings{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "RLP.Decode"
      },
      {
       "expr": "rate(nethermind_tree_node_hash_calculations{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Keccak"
      }
     ]
    },
    {
     "title": "Other DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_other_db_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[10s])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_other_db_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[10s])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Blocks DB (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_blocks_db_reads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_blocks_db_writes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DarkPool",
     "type": "graph",
     "description": "Unknown transactions in blocks",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "nethermind_dark_pool_ratio_level1{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "Level1 (not known)"
      },
      {
       "expr": "nethermind_dark_pool_ratio_level2{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}",
       "legendFormat": "level2 (not pending)"
      }
     ]
    },
    {
     "title": "1559-type transactions ratio",
     "type": "timeseries",
     "description": "Ratio of 1559-type transactions in the block.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "nethermind_eip1559transactions_ratio{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}