{
 "title": "Lighthouse Database",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(lighthouse_info{}, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(lighthouse_info{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(lighthouse_info{}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(lighthouse_info{}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "# Database Metrics\n\nMetrics collected from a Lighthouse Beacon Node regarding the core key-value database (e.g., LevelDB).\n\nCollected from the [`store`](https://github.com/sigp/lighthouse/tree/master/beacon_node/store) crate.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "On-Disk Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_disk_db_size {cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "### Reads per Minute\n\n\nThe global database reads per minute, expressed as operations and a cumulative bytes value.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
   "options": {
    "content": "### Writes per Minute\n\n\nThe global database writes per minute, expressed as operations and a cumulative bytes value.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "DB Read Operations per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_count_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} [1m])"
    }
   ]
  },
  {
   "title": "Avg DB Read Operations per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "rate(store_disk_db_read_count_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total {cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "Avg DB Throughput (Read) per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "rate(store_disk_db_read_bytes_total {cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "DB Read Write (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_count_total {cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total {cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} [1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "### Beacon state read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconState` (excluding action bytes read/write operations).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon State Read Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_read_overhead_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n/\nrate(store_beacon_state_read_overhead_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "title": "Beacon State Write Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_write_overhead_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n/\nrate(store_beacon_state_write_overhead_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "options": {
    "content": "### BeaconState read/writes\n\n\nNumber of `BeaconState` read/writes in operations and cumulative bytes.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon State Reads (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_read_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_write_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Beacon State Reads (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_read_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_write_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "### Beacon block read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconBlock` (excluding action bytes read/write operations).\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon Block Read Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_block_read_overhead_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n/\nrate(store_beacon_block_read_overhead_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "title": "Beacon Block Write Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_block_write_overhead_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n/\nrate(store_beacon_block_write_overhead_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "title": "Beacon Block Reads (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_read_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Beacon Block Writes (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_write_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "options": {
    "content": "### BeaconBlock read/writes\n\n\nNumber of `BeaconBlock` read/writes in operations and cumulative bytes.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon Block Reads (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_read_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Beacon Block Writes (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_write_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  }
 ]
}