{
 "title": "Lighthouse Summary",
 "description": "https://github.com/sigp/lighthouse-metrics/blob/master/dashboards/Summary.json",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(lighthouse_info{}, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(lighthouse_info{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(lighthouse_info{}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(lighthouse_info{}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# Lighthouse Metrics\n\nMetrics collected from a Lighthouse Beacon Node.\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg. Validator Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_total_validators_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Avg. Withdrawable Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_withdrawn_validators_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Avg. Current Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "slotclock_present_epoch{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Current Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "slotclock_present_slot{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lighthouse_info{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Avg. Slashed Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_slashed_validators_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Avg. Active Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(beacon_head_state_active_validators_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_loadavg_1{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "system_virt_mem_free_bytes{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Lighthouse Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 13 },
   "options": {
    "content": "### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slots since Best Block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_slot{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} - beacon_head_state_slot{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Justification (Min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} - beacon_head_state_current_justified_epoch{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} - beacon_head_state_finalized_epoch{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_attester{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Target Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_target_attester{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Head Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_head_attester{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Observed Attesters",
   "type": "graph",
   "description": "The number of attesters for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_attesters{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Previous Epoch Observed Aggregators",
   "type": "graph",
   "description": "The number of aggregators for which we have seen an attestation. That attestation is not necessarily included in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "# of Validators" }
   ],
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_aggregators{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Validator Balances",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Total Validator ETH" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_validator_balances_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} / 1000000000"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Total Validator ETH" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_active_validators_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Total Validator ETH" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_total_validators_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Finalized Root (hash shown as int)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 31 },
   "yaxes": [
    { "format": "sci", "label": "int(hash)" }
   ],
   "targets": [
    {
     "expr": "beacon_head_state_finalized_root{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Total Fork Choice Re-Orgs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 31 },
   "yaxes": [
    { "format": "none", "label": "Re-Orgs" }
   ],
   "targets": [
    {
     "expr": "beacon_fork_choice_reorg_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "options": { "content": "### Networking\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "libp2p Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "libp2p_peers{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "bargauge",
   "description": "Peers via client implementations",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "libp2p_peers_per_client{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{Client}}"
    }
   ]
  },
  {
   "title": "Unsolicited Discovery Requests/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discovery_requests{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Discovery Requests Per Second"
    }
   ]
  },
  {
   "title": "Active Discv5 Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discovery_sessions{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Queued Discovery Queries",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "discovery_queue_size{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Queued Discoveries"
    }
   ]
  },
  {
   "title": "Total Libp2p Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libp2p_total_bandwidth{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Libp2p Inbound Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libp2p_inbound_bytes{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "title": "Libp2p Outbound Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libp2p_outbound_bytes{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])",
     "legendFormat": "bytes/s"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 58 },
   "options": { "content": "### Gossipsub Metrics" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mesh peers per topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_mesh_peers_per_main_topic{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{topic_hash}}"
    }
   ]
  },
  {
   "title": "Average Peer Score per Topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_avg_peer_score_per_topic{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{topic_hash}}"
    }
   ]
  },
  {
   "title": "Mesh peers per subnet",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gossipsub_mesh_peers_per_subnet_topic{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{subnet}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 75 },
   "options": { "content": "### Logging\n\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Crit Logs Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "crit_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Error Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(error_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "Warn Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(warn_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "Info Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(info_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 83 },
   "options": {
    "content": "### Core BeaconChain Functions\n\nTiming of core `BeaconChain` functions and syncing.\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Processing Times (24s moving avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[30s])\n/\nrate(beacon_block_processing_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[30s])"
    }
   ]
  },
  {
   "title": "Find & Update Head Routine (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_fork_choice_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])\n/\nrate(beacon_fork_choice_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])"
    }
   ]
  },
  {
   "title": "Syncing Slots per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "none", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "sync_slots_per_second{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Block Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_block_root_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n/\nrate(beacon_block_processing_block_root_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "title": "State Tree Hash Times (5m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n/\nrate(beacon_block_processing_state_root_seconds_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 95 },
   "options": {
    "content": "### Database\n\nStats about the on-disk database (LevelDB)\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "On-Disk Database Size (Hot DB Only)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_disk_db_size{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 97 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"} [1m])"
    }
   ]
  },
  {
   "title": "Persist Beacon Chain Times (1m avg)",
   "type": "graph",
   "description": "Time taken to calculate the tree hash root of a BeaconState during block processing.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_persist_chain_sum{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])\n/\nrate(beacon_persist_chain_count{cluster=~\"$cluster\",instance=~\"$instance\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])"
    }
   ]
  }
 ]
}