name: github-action random auto-commit
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_GIT_WRITE_ACCESS_TOKEN }}
      - name: Update main branch
        run: |
          git config user.name "Update branch"
          git config user.email github-actions@github.com
          echo $RANDOM > random.txt
          git add random.txt
          git commit -m "Merged main branch on $(date +%F)"
      - name: Push the updated branch X
        run: |
          git push
